import SwiftUI

struct InteractionResultsSheetView: View {
    @Binding var isPresented: Bool
    let interactions: [DrugInteraction]
    let error: String?

    var body: some View {
        NavigationView {
            ZStack {
                Color(hex: "#404C42").ignoresSafeArea()

                if let error = error {
                    VStack(spacing: 20) {
                        Image(systemName: "exclamationmark.triangle.fill")
                            .font(.system(size: 50))
                            .foregroundColor(Color.orange)
                        Text("Error Checking Interactions")
                            .font(.title2).bold()
                            .foregroundColor(Color(hex: "#C7C7BD"))
                        Text(error)
                            .font(.body)
                            .foregroundColor(Color(hex: "#C7C7BD").opacity(0.8))
                            .multilineTextAlignment(.center)
                            .padding(.horizontal)
                    }
                    .padding()
                } else if interactions.isEmpty {
                    VStack(spacing: 20) {
                        Image(systemName: "checkmark.shield.fill")
                            .font(.system(size: 50))
                            .foregroundColor(Color.green)
                        Text("No Interactions Found")
                            .font(.title2).bold()
                            .foregroundColor(Color(hex: "#C7C7BD"))
                        Text("No significant interactions were found among your current medications.")
                            .font(.body)
                            .foregroundColor(Color(hex: "#C7C7BD").opacity(0.8))
                            .multilineTextAlignment(.center)
                            .padding(.horizontal)
                    }
                    .padding()
                } else {
                    ScrollView {
                        VStack(alignment: .leading, spacing: 16) {
                            Text("Potential Interactions Found")
                                .font(.title2).bold()
                                .foregroundColor(Color(hex: "#C7C7BD"))
                                .padding(.bottom, 8)

                            ForEach(interactions) { interaction in
                                InteractionRowView(interaction: interaction)
                            }
                            
                            Text("Remember: This information is generated by AI and should not replace professional medical advice. Always consult your doctor or pharmacist.")
                                .font(.caption)
                                .foregroundColor(Color(hex: "#C7C7BD").opacity(0.6))
                                .multilineTextAlignment(.center)
                                .padding(.top, 10)
                                .padding(.horizontal)

                        }
                        .padding()
                    }
                }
            }
            .navigationTitle("Interaction Results")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .navigationBarTrailing) {
                    Button("Done") {
                        isPresented = false
                    }
                    .foregroundColor(Color.pillrAccent)
                }
            }
        }
        .preferredColorScheme(.dark) // Assuming a dark theme from other views
    }
}

struct InteractionRowView: View {
    let interaction: DrugInteraction

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack {
                Text("\(interaction.drugA) + \(interaction.drugB)")
                    .font(.headline)
                    .foregroundColor(Color(hex: "#E0E0E0"))
                Spacer()
                Text(interaction.severity.rawValue)
                    .font(.caption.bold())
                    .padding(.horizontal, 8)
                    .padding(.vertical, 4)
                    .background(Color(hex: interaction.severity.color).opacity(0.8))
                    .foregroundColor(.black)
                    .cornerRadius(6)
            }

            Text(interaction.description)
                .font(.subheadline)
                .foregroundColor(Color(hex: "#C7C7BD").opacity(0.9))
            
            Text("Recommendation: \(interaction.recommendedAction)")
                .font(.footnote)
                .foregroundColor(Color(hex: "#C7C7BD").opacity(0.7))
        }
        .padding()
        .background(Color.black.opacity(0.15))
        .cornerRadius(10)
        .overlay(
            RoundedRectangle(cornerRadius: 10)
                .stroke(Color(hex: interaction.severity.color).opacity(0.3), lineWidth: 1)
        )
    }
}

struct InteractionResultsSheetView_Previews: PreviewProvider {
    static var previews: some View {
        // Preview with interactions
        InteractionResultsSheetView(
            isPresented: .constant(true),
            interactions: [
                DrugInteraction(drugA: "Warfarin", drugB: "Aspirin", severity: .major, description: "Increased risk of bleeding.", recommendedAction: "Consult doctor immediately."),
                DrugInteraction(drugA: "Lisinopril", drugB: "Ibuprofen", severity: .moderate, description: "May reduce effectiveness of Lisinopril and increase risk of kidney damage.", recommendedAction: "Monitor blood pressure and kidney function; discuss with doctor.")
            ],
            error: nil
        )
        .previewDisplayName("With Interactions")

        // Preview with no interactions
        InteractionResultsSheetView(
            isPresented: .constant(true),
            interactions: [],
            error: nil
        )
        .previewDisplayName("No Interactions")

        // Preview with error
        InteractionResultsSheetView(
            isPresented: .constant(true),
            interactions: [],
            error: "Failed to connect to the server. Please check your internet connection and try again."
        )
        .previewDisplayName("With Error")
    }
} 